language: lisp
sudo: required

env:
  matrix:
    - LISP=sbcl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

script:
  - cl -l prove -e '(ql:quickload :cl-vcr-tests) (or (prove:run :cl-vcr-tests) (uiop:quit -1))'


notifications:
  email:
    - raimonster@gmail.com
